#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

set -a
source .env
set +a

FS_DIR="storage/telephony/freeswitch/conf/directory/default"
GENERATED_FILE="${FS_DIR}/knvox-db-sip-accounts.xml"
BACKUP_DIR="${FS_DIR}/disabled-by-knvox-$(date +%Y%m%d-%H%M%S)"
EXPORT_DIR="exports/sip"
EXPORT_CSV="${EXPORT_DIR}/sip_accounts_provisioning_$(date +%Y%m%d-%H%M%S).csv"

mkdir -p "${FS_DIR}" "${EXPORT_DIR}"

echo "===================================="
echo " KNVOX FREESWITCH SIP SYNC"
echo "===================================="
echo ""

if [ -z "${FS_DEFAULT_PASSWORD:-}" ]; then
  echo "ERROR: FS_DEFAULT_PASSWORD manquant dans .env"
  exit 1
fi

echo "[1/6] Bootstrap comptes 1000-1019 en DB si manquants"

./scripts/compose.sh exec -T postgres psql \
  -U "$POSTGRES_USER" \
  -d "$POSTGRES_DB" \
  -v fs_pass="$FS_DEFAULT_PASSWORD" <<'SQL'
DO $$
DECLARE
    i INTEGER;
BEGIN
    FOR i IN 1000..1019 LOOP
        INSERT INTO billing.sip_accounts(
            username,
            customer_code,
            display_name,
            auth_password,
            realm,
            enabled,
            cps_limit,
            max_concurrent_calls,
            notes
        )
        VALUES (
            i::TEXT,
            'TEST1000',
            'KNVOX SIP ' || i::TEXT,
            :'fs_pass',
            'knvox.local',
            true,
            1,
            2,
            'Bootstrap FreeSWITCH default range'
        )
        ON CONFLICT (username) DO NOTHING;
    END LOOP;

    UPDATE billing.sip_accounts
    SET auth_password = :'fs_pass',
        updated_at = now()
    WHERE username = '1000'
      AND auth_password = 'managed-by-freeswitch';
END $$;
SQL

echo ""
echo "[2/6] Extraction comptes SIP actifs 1000-1019"

TMP_DATA="$(mktemp)"

./scripts/compose.sh exec -T postgres psql \
  -U "$POSTGRES_USER" \
  -d "$POSTGRES_DB" \
  -AtF $'\t' \
  -c "
    SELECT
      username,
      customer_code,
      COALESCE(display_name, username),
      auth_password,
      COALESCE(realm, 'knvox.local'),
      cps_limit,
      max_concurrent_calls
    FROM billing.sip_accounts
    WHERE enabled = true
      AND username ~ '^(100[0-9]|101[0-9])$'
    ORDER BY username;
  " > "${TMP_DATA}"

COUNT="$(wc -l < "${TMP_DATA}" | tr -d ' ')"

if [ "${COUNT}" = "0" ]; then
  echo "ERROR: aucun compte SIP actif trouvé dans 1000-1019"
  rm -f "${TMP_DATA}"
  exit 1
fi

echo "Comptes trouvés : ${COUNT}"

echo ""
echo "[3/6] Désactivation anciens XML FreeSWITCH en conflit"

while IFS=$'\t' read -r username customer display password realm cps concurrent; do
  MATCHES="$(grep -RIlE "<user[[:space:]][^>]*id=[\"']${username}[\"']" "${FS_DIR}" 2>/dev/null || true)"
  if [ -n "${MATCHES}" ]; then
    mkdir -p "${BACKUP_DIR}"
    while IFS= read -r file; do
      [ -z "${file}" ] && continue
      [ "$(basename "${file}")" = "knvox-db-sip-accounts.xml" ] && continue
      echo "Backup conflit user ${username}: ${file}"
      mv "${file}" "${BACKUP_DIR}/$(basename "${file}").bak"
    done <<< "${MATCHES}"
  fi
done < "${TMP_DATA}"

echo ""
echo "[4/6] Génération XML FreeSWITCH : ${GENERATED_FILE}"

python3 - "${TMP_DATA}" "${GENERATED_FILE}" <<'PY'
import sys
import html
from pathlib import Path

data_file = Path(sys.argv[1])
out_file = Path(sys.argv[2])

rows = []
for line in data_file.read_text().splitlines():
    if not line.strip():
        continue
    parts = line.split("\t")
    while len(parts) < 7:
        parts.append("")
    rows.append(parts[:7])

xml = []
xml.append("<include>")
xml.append("  <!-- Generated by KNVOX. Do not edit manually. -->")

for username, customer, display, password, realm, cps, concurrent in rows:
    u = html.escape(username)
    c = html.escape(customer)
    d = html.escape(display or username)
    p = html.escape(password)
    r = html.escape(realm or "knvox.local")

    xml.append(f'  <user id="{u}">')
    xml.append("    <params>")
    xml.append(f'      <param name="password" value="{p}"/>')
    xml.append("      <param name=\"vm-password\" value=\"0000\"/>")
    xml.append("    </params>")
    xml.append("    <variables>")
    xml.append(f'      <variable name="accountcode" value="{c}"/>')
    xml.append(f'      <variable name="user_context" value="default"/>')
    xml.append(f'      <variable name="effective_caller_id_name" value="{d}"/>')
    xml.append(f'      <variable name="effective_caller_id_number" value="{u}"/>')
    xml.append(f'      <variable name="knvox_customer_code" value="{c}"/>')
    xml.append(f'      <variable name="knvox_realm" value="{r}"/>')
    xml.append("    </variables>")
    xml.append("  </user>")

xml.append("</include>")
out_file.write_text("\n".join(xml) + "\n")
PY

chmod 600 "${GENERATED_FILE}"

echo ""
echo "[5/6] Export CSV provisioning local : ${EXPORT_CSV}"

{
  echo "username,customer_code,display_name,password,realm,cps_limit,max_concurrent_calls"
  while IFS=$'\t' read -r username customer display password realm cps concurrent; do
    printf '"%s","%s","%s","%s","%s","%s","%s"\n' \
      "$username" "$customer" "$display" "$password" "$realm" "$cps" "$concurrent"
  done < "${TMP_DATA}"
} > "${EXPORT_CSV}"

chmod 600 "${EXPORT_CSV}"

echo ""
echo "[6/6] Reload FreeSWITCH XML"

if [ -x ./scripts/fs_cli.sh ]; then
  ./scripts/fs_cli.sh -x "reloadxml" || true
  ./scripts/fs_cli.sh -x "sofia profile internal rescan" || true
else
  ./scripts/compose.sh exec -T freeswitch fs_cli -x "reloadxml" || true
  ./scripts/compose.sh exec -T freeswitch fs_cli -x "sofia profile internal rescan" || true
fi

rm -f "${TMP_DATA}"

echo ""
echo "Sync terminé."
echo "XML généré : ${GENERATED_FILE}"
echo "CSV local  : ${EXPORT_CSV}"
echo ""
echo "ATTENTION : le CSV contient les mots de passe SIP. Il est ignoré par Git."
